<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>1.0.1</Version>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Ardalis.SmartEnum" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<None Include="../../README.md" Pack="true" PackagePath="" />
	</ItemGroup>

</Project>
