<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.1</Version>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId></PackageId>
    <Title>BaseCrud.Abstractions</Title>
    <Version></Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseCrud\BaseCrud.csproj" />
  </ItemGroup>

</Project>
