<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Version>1.0.0</Version>
	<TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseCrud.Abstractions\BaseCrud.Abstractions.csproj" />
    <ProjectReference Include="..\BaseCrud.EntityFrameworkCore\BaseCrud.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\BaseCrud.PrimeNg\BaseCrud.PrimeNg.csproj" />
    <ProjectReference Include="..\BaseCrud\BaseCrud.csproj" />
    <None Include="../../README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
